--- # Copy and command module example 
- hosts: web1
  connection: ssh
  gather_facts: yes
  become: yes
  vars_files:
    - conf/credentials.yml
    - conf/copyright.yml
    - conf/webdefaults.yml
    - conf/users.yml
  tasks:
  - name: Copy from the files directory test script
    action: copy src=files/testscript.sh dest=/home/cloud_user/testscript.sh owner=cloud_user group=cloud_user mode=0755 backup=yes
  - name: Make test script executable
    file:
      path: /home/cloud_user/testscript.sh
      mode: "+x"
  - name: Execute test script
    command: ./testscript.sh
    args:
      chdir: /home/cloud_user
 
