--- # Copy and command module example 
- hosts: all
  connection: ssh
  gather_facts: yes
  become: yes
  vars_files:
    - conf/credentials.yml
    - conf/copyright.yml
    - conf/webdefaults.yml
    - conf/users.yml
  tasks:
  - name: Copy from the files directory test script
    action: copy src=files/testscript.sh dest=/home/test/testscript.sh owner=test group=test mode=0755 backup=yes
  - name: Make test script executable
    file:
      path: /home/test/testscript.sh
      mode: "+x"
  - name: Execute test script
    command: ./testscript.sh
    args:
      chdir: /home/test
 
