--- # My First Playbook
- hosts: webhosts
  connection: ssh
  gather_facts: no
  vars_files:
    - conf/credentials.yml
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars:
    - playbook_version: '0.2'
  vars_prompt:
    - name: "interesting_var"
      prompt: "Input variable to debug (blank = 'vars' which is all variables)"
  tasks:
    - name: debug variable
      debug: 
        var: "{{ interesting_var | default('vars', true) }}"
