--- # htpasswd example 
- hosts: webhosts
  connection: ssh
  gather_facts: no
  become: yes
  vars_files:
  - vars/users.yml
  vars:
  - playbook_version: 1.1
  tasks:
    - name: Install python-passlib package
      yum:
        name: 
          - python-passlib  
        state: present

    - name: Add user to htpasswd
      htpasswd:
        path: /etc/httpd/.htpasswd
        name: test
        password: test
        owner: root
        group: root
        mode: 0755

