--- # My First Playbook
- hosts: webhosts
  connection: ssh
  gather_facts: no
  vars_files:
    - conf/credentials.yml
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars:
    - playbook_version: '0.2'
  tasks:
    - name: Print $HOME
      debug: 
        msg: "{{ lookup('env','HOME') }}"
