--- # script module example 
- hosts: all
  connection: ssh
  gather_facts: yes
  become: yes
  vars_files:
    - conf/credentials.yml
    - conf/copyright.yml
    - conf/webdefaults.yml
    - conf/users.yml
  tasks:
  - name: Execute script remotely
    script: /home/test/playbooks/files/testscript.sh
    register: script_output

  - debug: 
      var: script_output
