--- # Shell module example
- hosts: all
  connection: ssh
  gather_facts: no
  become: no
  vars_files:
  - vars/users.yml
  vars:
  - playbook_version: 1.1
  tasks:
    - name: Create log directory
      file: 
        path: /home/test/logs
        state: directory
        owner: test
        group: test
        mode: 0755
    - name: Executing a remote command - uptime
      shell: /usr/bin/uptime >> uptime.log
      args:
        chdir: logs/
        creates: uptime.log
