--- # Update all packages
- hosts: all
  connection: ssh
  gather_facts: yes
  become: yes
  vars_files:
    - conf/credentials.yml
    - conf/copyright.yml
    - conf/webdefaults.yml
    - conf/users.yml
  tasks:
    - name: Update all packages via YUM
      yum:
        name: '*'
        state: latest
   #     update_cache: yes 

 
